---
title: "Mood"
author: "Arda Ergin"
date: "2024-04-02"
output: html_document
---

# Setup
```{r}
library(dplyr)
library(tidyr)
```

```{r}
data_raw <- read.csv("data.csv")
```

# Start

How many variables and how many participants?
```{r}
unique(data_raw$variable)
unique(data_raw$id)
```

Some Fixes:
```{r}
# Getting a better ID column:
data_0 <- data_raw %>%
  mutate(ID = as.numeric(sapply(
    strsplit(id, split = '\\.'), function(x) x[2])))

# Changing the name for the "X" variable
colnames(data_0)[1] <- "obs_number"

# Getting rid of the 
data_1 <- data_0[,c("obs_number", "time", "ID", "variable", "value")]
```

Long to Wide Transformation:
```{r}
wide_data <- tidyr::pivot_wider(
  data_0, 
  names_from = variable, 
  values_from = value)
```

Looking at Just one Individual
```{r}
data_1 <- wide_data %>% filter(id == "AS14.01")
```

# Investigating Variables
## mood
```{r}
hist(wide_data$mood, breaks = 10)
```

## circumplex.arousal
```{r}
par(mfrow = c(1,2))
hist(wide_data$circumplex.arousal); hist(wide_data$circumplex.valence)
```


## appCat.game
```{r}
gamers <- wide_data %>% filter(appCat.game > 300)
hist(log(wide_data$appCat.game), breaks = 100)
boxplot(log(wide_data$appCat.game))
```


## appCat.game

```{r}
max(wide_data$appCat.game)
summary(wide_data$sms)
```





